Added new endpoint to tak in CSV file and then call the response serv…
ONSdigital/fwmt-staff-service pull request #10
Opened 2018-06-21 09:10 UTC by spdiaz1000

…ice endpoint to create new users within the data base

2018-06-21 14:41 UTC, garethTurner commented on src/main/java/uk/gov/ons/fwmt/staff_service/data/dto/UserDTO.java
> +    public Boolean activeDate;
Should just be active

2018-06-25 16:15 UTC, JacobHarrisonQA commented on src/main/java/uk/gov/ons/fwmt/staff_service/controller/StaffController.java
> +    Reader reader = new InputStreamReader(file.getInputStream());
extract this into a separate method in a service so it can be tested

2018-06-26 12:10 UTC, garethTurner requested changes

2018-06-26 12:10 UTC, garethTurner commented on src/main/resources/wsdl/Messaging_MessageQueueWs.wsdl
> +          <!--<s:element minOccurs="0" maxOccurs="unbounded" name="UserDTO" type="s1:UserType" />-->
Dont think these should have been changed

2018-06-26 14:42 UTC, JacobHarrisonONS approved these changes

2018-06-26 14:43 UTC, garethTurner approved these changes

2018-06-26 14:45 UTC, merged